manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
  projects:
    - name: sdk_nrf
      repo-path: sdk-nrf
      path: nrf
      remote: ncs
      revision: v2.7.0
      import: true
  self:
    path: ble_audio
