manifest:
  remotes:
    - name: origin
      url-base: git@github.com:paltatech
  projects:
    - name: sdk_nrf
      repo-path: vx_sdk_nrf
      path: nrf
      remote: origin
      revision: manifest-rev
      import: true
    - name: zephyr_boards
      repo-path: vx_zephyr_boards
      path: zephyr_boards
      remote: origin
      revision: develop
      import: false
  self:
    path: ble_audio
