#ifndef AUDIO_DEFS_H_
#define AUDIO_DEFS_H_

#define AUDIO_SAMPLE_RATE_HZ	    48000
#define AUDIO_FRAME_DURATION_US	    10000
#define AUDIO_MAX_SAMPLES_PER_FRAME ((AUDIO_FRAME_DURATION_US * AUDIO_SAMPLE_RATE_HZ) / 1000000)

#endif /* AUDIO_DEFS_H_ */
